version: "2"
services:
  web:
    build: .
    ports:
      - "80:3001"
    links:
      - mongodb
    environment:
      - MONGODB=mongodb://mongodb/shop
  mongodb:
    image: mongo
    ports:
      - "27018"

  mongo_seed:
    build: ./mongo-seed
    links:
      - mongodb